# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Warning_Form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Warning_Form(object):
    def setupUi(self, Warning_Form):
        Warning_Form.setObjectName("Warning_Form")
        Warning_Form.resize(354, 130)
        Warning_Form.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.label_name = QtWidgets.QLabel(Warning_Form)
        self.label_name.setGeometry(QtCore.QRect(50, 10, 281, 31))
        self.label_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_name.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_name.setObjectName("label_name")
        self.label = QtWidgets.QLabel(Warning_Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/PBL_Image&Icon/warning.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_name_2 = QtWidgets.QLabel(Warning_Form)
        self.label_name_2.setGeometry(QtCore.QRect(70, 100, 201, 21))
        self.label_name_2.setObjectName("label_name_2")
        self.frame = QtWidgets.QFrame(Warning_Form)
        self.frame.setGeometry(QtCore.QRect(-1, 50, 401, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txt_battery_level = QtWidgets.QLabel(self.frame)
        self.txt_battery_level.setGeometry(QtCore.QRect(70, 10, 41, 21))
        self.txt_battery_level.setObjectName("txt_battery_level")
        self.label_name_3 = QtWidgets.QLabel(self.frame)
        self.label_name_3.setGeometry(QtCore.QRect(120, 10, 141, 21))
        self.label_name_3.setObjectName("label_name_3")

        self.retranslateUi(Warning_Form)
        QtCore.QMetaObject.connectSlotsByName(Warning_Form)

    def retranslateUi(self, Warning_Form):
        _translate = QtCore.QCoreApplication.translate
        Warning_Form.setWindowTitle(_translate("Warning_Form", "Alert Battery"))
        self.label_name.setText(_translate("Warning_Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#e01b24;\">Your Battery is running low !</span></p></body></html>"))
        self.label_name_2.setText(_translate("Warning_Form", "<html><head/><body><p><span style=\" font-size:10pt; color:#000000;\">you might want to plug in your PC</span></p></body></html>"))
        self.txt_battery_level.setText(_translate("Warning_Form", "<html><head/><body><p>10%</p></body></html>"))
        self.label_name_3.setText(_translate("Warning_Form", "<html><head/><body><p>of battery remaining</p></body></html>"))
import Forms.Icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Warning_Form = QtWidgets.QWidget()
    ui = Ui_Warning_Form()
    ui.setupUi(Warning_Form)
    Warning_Form.show()
    sys.exit(app.exec_())
